### ISSUE TITLE
Figure out how to input world info into network inputs.

### ISSUE THREAD

**Issue by selfint** [tomaster777/Creatures#12]

**Comment by Tadaboody** [comment]
How do you plan on doing it?

**Comment by selfint** [comment]
Made CreatureNetworkInput named tuple, and simulation.info_to_vec function

**Comment by selfint** [comment]
Info to vec has more documentation in it

**Comment by Tadaboody** [comment]
You didn't push it. when you do - try mentioning this commit.

add "Closes #12" to the message and it'll even mark this issue as closed

**Comment by Tadaboody** [comment]
Check out the "References" part [here](https://guides.github.com/features/issues/#notifications)

**Comment by selfint** [comment]
Will do :D

**Comment by selfint** [comment]
did it
